[package]
name = "raw-syscall"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
mio = { version = "1.0.4", features = ["net", "os-poll"] }
